hpa:
  cpuUtilization: '90'
  enabled: false
  maxReplicas: '3'
  memoryUtilization: 450Mi
  minReplicas: '1'
image:
  imagePullSecrets:
    - name: ghcr-secret
  pullPolicy: IfNotPresent
  repository: ghcr.io/fitnest-code/gateway-backend
  tag: production-9fb4e55
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '64m'
  backend:
    service:
      name: ''
      port: 80
  className: nginx
  enabled: true
  hosts:
    - host: api.fitnest.az
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - api.fitnest.az
      secretName: fitnest-wildcard-tls
networkPolicy:
  enabled: true
replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi
service:
  port: 80
  targetPort: 8080
  type: ClusterIP
vaultEnv: production
