hpa:
  cpuUtilization: '90'
  enabled: false
  maxReplicas: '3'
  memoryUtilization: 450Mi
  minReplicas: '1'
image:
  imagePullSecrets:
    - name: ghcr-secret
  pullPolicy: IfNotPresent
  repository: ghcr.io/fitnest-code/gateway-backend
  tag: production-9ce9384
ingress:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '64m'
  backend:
    service:
      name: ''
      port: 80
  className: nginx
  enabled: true
  hosts:
    - host: api-dev.fitnest.az
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - api-dev.fitnest.az
      secretName: fitnest-tls
networkPolicy:
  enabled: true
replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 384Mi
  limits:
    cpu: 1000m
    memory: 768Mi
service:
  port: 80
  targetPort: 8080
  type: ClusterIP
vaultEnv: development
