{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "api-gateway.fullname" . }}-vs
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Values.istio.gateway.name }}
  hosts:
    {{- toYaml .Values.istio.virtualService.hosts | nindent 4 }}
  http:
    - match:
      {{- range .Values.istio.virtualService.paths }}
        - uri:
            prefix: {{ . }}
      {{- end }}
      {{- range .Values.istio.virtualService.exactPaths }}
        - uri:
            exact: {{ . }}
      {{- end }}
      route:
        - destination:
            host: {{ include "api-gateway.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
